# Created with Komac v1.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Microsoft.WindowsTerminal.Preview
PackageVersion: 1.18.1462.0
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://github.com/microsoft/terminal
PublisherSupportUrl: https://github.com/microsoft/terminal/issues
Author: Microsoft Corporation
PackageName: Windows Terminal Preview
PackageUrl: https://github.com/microsoft/terminal
License: MIT
LicenseUrl: https://github.com/microsoft/terminal/blob/master/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
CopyrightUrl: https://github.com/microsoft/terminal/blob/master/LICENSE
ShortDescription: The new Windows Terminal, a tabbed command line experience for Windows.
Description: |-
  Windows Terminal is a modern terminal application for users of command line tools and shells like Command Prompt, PowerShell, and Windows Subsystem for Linux (WSL).
   Its main features include multiple tabs, panes, Unicode and UTF-8 character support, a GPU accelerated text rendering engine, and the ability to create your own themes and customize text, colors, backgrounds, and shortcut key bindings.
Moniker: terminal-preview
Tags:
- command-line
- command-prompt
- console
- developer-tools
- powershell
- shell
- utilities
- wsl
ReleaseNotes: |-
  Wow, it looks like 1.18 had a bunch of issues. Thanks for bearing with us and using the Preview channel!

  Bug fixes for the new rendering engine:
  - Glyphs that extend above or below the screen (like certain NerdFont varieties) no longer cause rendering failures (#15403)
  - There should be 100% fewer leftover cursor pieces during scrolling (#15427)
  - DRCS soft fonts no longer cause crashes (#15419)
  - We've improved scrolling and device invalidation (#15425)
  - wt --help now no longer emits a crash log after it exits (oops) (#15445)
  - In general (outside of the --help case,) Terminal should crash even less on exit (#15451)
  - We've stamped out some crashes on resize during shutdown (#15457)
  - The new environment variable support will now always expand PATH, even if it is not a REG_EXPAND_SZ (#15444) (thanks @sotteson1!)
  - OpenConsole: block selection now properly records line breaks (#15423)
  - The "Developer Command Prompt" profiles are no longer totally busted (#15439)
  - Terminal no longer crashes when you have focusFollowMouse mode enabled (#15420)
  Asset Hashes
  - Microsoft.WindowsTerminalPreview_1.18.1462.0_8wekyb3d8bbwe.msixbundle
  - SHA256 60BF2D35DAC57DC2878C71C581CC3F000E1875A08AF318615E8FA6DD9288BCDA
ReleaseNotesUrl: https://github.com/microsoft/terminal/releases/tag/v1.18.1462.0
ManifestType: defaultLocale
ManifestVersion: 1.4.0
