# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.OfficeDeploymentTool
PackageVersion: 16.0.16227.20258
MinimumOSVersion: 10.0.0.0
InstallerSwitches:
  Silent: /quiet /passive /extract:"C:\Program Files\OfficeDeploymentTool"
  SilentWithProgress: /quiet /passive /extract:"C:\Program Files\OfficeDeploymentTool"
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_16227-20258.exe
  InstallerSha256: A39D49E09E0DD81D7FDAB8E22A6D28894615B948E9596A211EAAF094A59B4F9B
ManifestType: installer
ManifestVersion: 1.4.0
