# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: MediaArea.MediaInfo.GUI
PackageVersion: 23.04
PackageLocale: en-US
Publisher: MediaArea.net
PublisherUrl: https://mediaarea.net/
PublisherSupportUrl: https://mediaarea.net/MediaInfo/Support
PrivacyUrl: https://mediaarea.net/Privacy
PackageName: MediaInfo
PackageUrl: https://mediaarea.net/MediaInfo
License: BSD-2-Clause
LicenseUrl: https://mediaarea.net/MediaInfo/License
ShortDescription: Convenient unified display of the most relevent technical and tag data for video and audio files.
Moniker: mediainfo-gui
Tags:
- video-metadata
ManifestType: defaultLocale
ManifestVersion: 1.4.0
